# Generated by Django 5.2.2 on 2025-06-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0002_knowledgebaseentry_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebaseentry',
            name='title',
        ),
    ]
