# Generated by Django 5.2.2 on 2025-06-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0004_assistant_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='tag_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
