# Generated by Django 5.2.2 on 2025-06-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0005_alter_assistant_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20),
        ),
    ]
